---
title: "Create Dataset"
author: "Aaron Schroeder"
date: "11/17/2021"
output: html_document
dataset:
  citation:
      title: "Social Data Commons: Education & Training: Virginia SOL Scores"
      dsDescriptionValue: "Virginia Standards of Learning Test Scores collected by the Virginia Department of Education (VDOE)"
      subject: "Social Sciences (Ex: Education, Politics, Sociology, Economics, Psychology)"
      productionDate: "2021-11-17"
      author:
        - authorName: "Schroeder, Aaron"
          authorAffiliation: "Univeristy of Virginia"
        - authorName: "Charankevich, Hanna"
          authorAffiliation: "Univeristy of Virginia"
        - authorName: "Niagra, Bob"
          authorAffiliation: "Univeristy of Waterloo"
      datasetContact:
        - datasetContactEmail: "ads7fg@virginia.edu"
          datasetContactName: "Schroeder, Aaron"
        - datasetContactEmail: "hc2cc@virginia.edu"
          datasetContactName: "Charankevich, Hanna"
  geospatial:
    geographicCoverage:
      country: "United States"
      state: "Virginia"
    geographicUnit:
      - "State Health District"
      - "County"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

# CREATE DATASET FIRST WITH dataset_create.Rmd

## This will give you a dataset to which you can add files

## This will also set the dataset DOI

## Get dataset DOI

```{r}
dataset_doi <- readLines(here::here("data/dataset_doi"))[1]
```

## Get data from database

```{r data}
dat_file_name <- "va_hdct_vdoe_2019_2021_3rd_grade_median_read_score"

con <- get_db_conn()
dat <- DBI::dbReadTable(con, c("dc_education_training", dat_file_name))
DBI::dbDisconnect(con)

assign(dat_file_name, dat)
```

## Write to compressed file

```{r compress}
dat_file_path <- here::here(paste0("data/", "va_hdct_vdoe_2019_2021_3rd_grade_median_read_score", ".csv.xz"))

readr::write_csv(get(dat_file_name),
                 xzfile(dat_file_path, compression = 9))
```

## Upload Files to Dataverse Dataset

```{r upload}
add_dataset_file(
  file = dat_file_path,
  dataset = dataset_doi,
  key = Sys.getenv("DATAVERSE_KEY"),
  server   = Sys.getenv("DATAVERSE_SERVER"),
  description = dat_file_name
)
```
